### ISSUE TITLE
Automatically increment build number on upload?

### ISSUE THREAD

**Issue by kyleabeauchamp** [Binstar/binstar#109]
So we have a workflow where we upload packages to https://binstar.org/omnia/mdtraj/ on either the `main` or the `jenkins` channel, where we use the `main` channel to hold our "production" releases and the `jenkins` channel to hold the pre-release candidates that are produced by our CI system.  At release time, we plan on manually switching the tarballs from jenkins to main.  

However, we've found that uploading a file to `jenkins` channel will overwrite the same file in the `main` channel--essentially deleting a release version, as it's no longer publically accessible.  Obviously we're using the --force flag here.   

I wonder if a good solution to this would be a flag `--increment` that first checks whether a package with the same version has already been uploaded, then increments the build number accordingly to prevent overwrite.  Right now, the build number is set in the conda recipe, but I'd prefer to avoid having to edit the recipe for this, as the recipes are under version control.

**Comment by srossross** [comment]
CC @ilanschnell

**Comment by tswicegood** [comment]
Hey @kyleabeauchamp -- trying to understand what's happened here.  You have a released 1.2.0 version of omnia, but you're building newer versions of the same thing?  This sounds like a perfect case for modifying the build number.  The build number lets you say "this is the same as this other version, but the build process was a little more refined.  If it's a truly new version, I would recommend changing the version number.

Reading through https://github.com/omnia-md/conda-recipes/issues/80 it sounds like you might be working on a dev release, in this case I follow the pattern of adding `alpha` or `beta` to my version numbers.  For example, `1.2alpha.0` is what would be used until I'm ready to move to final testing, then `1.2beta.0` for final bug squashing before removing the `beta` piece entirely for the final release.

That said, you can change the build number (or version for that matter) programmatically using templates and environment variables.  For example, you can add this:

```yaml
build:
  number: {{ environ.get('MY_BUILD_NUMBER', 0) }}
```

`environ` is mapped to `os.environ` and using `.get()` lets it default to 0 when its not set.  With this style, you would need to modify your Jenkins setup to set `MY_BUILD_NUMBER` to something different each time it builds.  You could even use the Jenkin's number directly with `environ.get('BUILD_NUMBER')`.

Make sure you have the `jinja2` package installed in the root environment along side `conda` and `conda-build` before doing this: otherwise your `meta.yaml` file won't be parseable.

Quick how this works (you can skip if you're interested in just using it): Conda recipes attempt to parse themselves via `jinja2` when the module can be imported.  That turns your `meta.yaml` file into a full-blown template that you can do template things with.  Presently, `os.environ` is assigned to `environ` inside the recipe file so anything that's accessible as an environment variable is accessible inside your template.

Good luck!

**Comment by kyleabeauchamp** [comment]
Thanks, this idea could help us improve our build system.

We are working on a "dev release", but it's a little bit different because our big goal is to release a giant metapackage whose sub-packages (e.g. MDTraj) are already released versions.  Thus, the source code (and thus the MDTraj conda recipe) is released (not alpha or beta), but what we're trying to test are the actual binary uploads.  That's why we were trying to use the channels to help separate the various builds we have.  

I'll close this now, as we'll experiment with this.
